---
title: 'CUNY MSDS Data 605 HW #13'
author: "Samantha Deokinanan"
date: "24th November, 2019"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '4'
---
***  
### Problem 1
Use integration by substitution to solve the integral below:

$\int 4e^{-7x}dx \\$

Let $u = -7x$ and $du = -7dx$, thus $dx = \frac{du}{-7}$. Substituting, we get   
$= 4\int e^u\frac{du}{-7}$  
$= \frac{4}{-7}\int e^u du$  
$= \frac{4}{-7} e^u$  
$= \frac{4}{-7} e^{-7x} + constant$  

***
### Problem 2
Biologists are treating a pond contaminated with bacteria. The level of contamination is changing at a rate of $\frac {dN}{dt}=\frac {-3150}{t^{4}}−220$ bacteria per cubic centimeter per day, where $t$ is the number of days since treatment began. Find a function $N(t)$ to estimate the level of contamination if the level after 1 day was 6530 bacteria per cubic centimeter.  

$\frac {dN}{dt}=\frac {-3150}{t^{4}}−220$  
$dN=(\frac {-3150}{t^{4}}−220) dt$  
$\int dN=\int\frac {-3150}{t^{4}} dt−\int 220 dt$  
$N(t)=\frac {-1050}{t^{3}}−220t + constant$    

With $N(1) = 6530$, 

$N(1)=\frac {-1050}{1^{3}}−220(1) + constant=6530$  
$constant = 6530 - 1050 +220$  
$constant = 5700$

Thus, the function $N(t)$ to estimate the level of contamination is $N(t) = \frac {1050}{t^3}-220t + 5700$.

***
### Problem 3
Find the total area of the red rectangles in the figure below, where the equation of the line is $f(x) = 2x-9$.

$A_{1} = (5.5-4.5)*1 = 1$  
$A_{2} = (6.5-5.5)*3 = 3$  
$A_{3} = (7.5-6.5)*5 = 5$  
$A_{4} = (8.5-7.5)*7 = 7$  
$A_{total} = 1 + 3 + 5 + 7 = 16$  

***
### Problem 4
Find the area of the region bounded by the graphs of the given equations.

$y = x^{2}-2x-2$  
$y = x + 2$

```{r}
curve((x^2) - 2*x - 2, -2, 5)
curve(x + 2, add = TRUE, -2, 5)
```

$A = \int\limits_{-1}^{4}x+2 dx -\int\limits_{-1}^{4}x^2 -2x-2 dx$  
$A = \frac{1}{2}x^2|_{-1}^{4} +2x|_{-1}^{4} -[\frac{1}{3}x^3 - x^2 -2x]|_{-1}^{4}$  
$A = -[\frac{1}{3}x^3 - \frac{3}{2}x^2 -4x]|_{-1}^{4}$  
$A = [\frac{3}{2}x^2 +4x -\frac{1}{3}x^3]|_{-1}^{4}$   
$A = [\frac{3}{2}(4)^2 +4(4) -\frac{1}{3}(-1)^3]-[\frac{3}{2}(-1)^2 +4(-1) -\frac{1}{3}(-1)^3]$  
$A = 18.66 - (-2.17)$  
$A = 20.83$  

***
### Problem 5
A beauty supply store expects to sell 110 flat irons during the next year. It costs \$3.75 to store one flat iron for one year. There is a fixed cost of \$8.25 for each order. Find the lot size and the number of orders per year that will minimize inventory costs.

Let f be the number of flat irons ordered. 

$Cost_{storage} = \$3.75 \times \frac {f}{2} = 1.875\times f$  
$Cost_{order} = \$8.25 \times \frac {110}{f} = \frac {907.5}{f}$  
$Cost_{inventory} = 1.875f + \frac {907.5}{f}$  

Next, we solve to find find the extremun.

$f'(x) = 1.875 - \frac {907.5}{f^{2}} = 0$  
$1.875 = \frac {907.5}{f^{2}}$  
$1.875f^{2} = 907.5$  
$f = \sqrt{\frac {907.5}{1.875}}$  
$f = 22$  

With the second derivative being positive, 22 flat irons is the lot size for the minimum number of flat irons that should be order. With this, the number of orders per year that will minimize inventory costs is ($\frac {110}{22}=$) 5 orders.

***
### Problem 6
Use integration by parts to solve the integral below.

$\int ln(9x)*x^6dx$  

If $u = ln(9x)$, then $du = \frac {1}{x}dx$.  
If $dv = x^6 dx$, then $v = \frac {x^{7}}{7}$  
$\int u*dv = u*v - \int v*du$  
$= \frac {x^{7}}{7}ln(9x) - \frac {1}{7}\int x^6dx$  
$= \frac {x^{7}}{7}ln(9x) - \frac {x^{7}}{49} + constant$  

***
### Problem 7
Determine whether f(x) is a probability density function
on the interval $[1, e^{6}]$. If not, determine the value of the definite integral.

$f(x) = \frac {1}{6x}$

A function is a PDF on the interval if the value is non-negative, and the definite integral is equal to 1.

$\int\limits_1^{e^6}{\frac{1}{6x}dx}$  
$= \frac{ln(x)}{6}|_1^{e^6}$  
$= \frac{ln(e^6)-ln(1)}{6}$  
$= \frac{6-0}{6}$  
$= 1$  

***